# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nsfw.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nsfw.proto',
  package='nsfw_detection_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nnsfw.proto\x12\x11nsfw_detection_pb\"7\n\x0bUnsafeFrame\x12\x0e\n\x06second\x18\x01 \x01(\x02\x12\x18\n\x10nsfw_probability\x18\x02 \x01(\x02\"=\n\x16\x44\x65tectFromVideoRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\x12\x14\n\x0cvideo_format\x18\x02 \x01(\t\"=\n\x16\x44\x65tectFromImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"\x8b\x01\n\x16VideoDetectionResponse\x12:\n\x0e\x63lassification\x18\x01 \x01(\x0e\x32\".nsfw_detection_pb.Classifications\x12\x35\n\runsafe_frames\x18\x02 \x03(\x0b\x32\x1e.nsfw_detection_pb.UnsafeFrame\"n\n\x16ImageDetectionResponse\x12:\n\x0e\x63lassification\x18\x01 \x01(\x0e\x32\".nsfw_detection_pb.Classifications\x12\x18\n\x10nsfw_probability\x18\x02 \x01(\x02*M\n\x0f\x43lassifications\x12\x08\n\x04Safe\x10\x00\x12\x10\n\x0cProbablySafe\x10\x01\x12\x12\n\x0eProbablyUnsafe\x10\x02\x12\n\n\x06Unsafe\x10\x03\x32\xed\x01\n\x19NsfwDetectionProtoService\x12g\n\x0f\x44\x65tectFromVideo\x12).nsfw_detection_pb.DetectFromVideoRequest\x1a).nsfw_detection_pb.VideoDetectionResponse\x12g\n\x0f\x44\x65tectFromImage\x12).nsfw_detection_pb.DetectFromImageRequest\x1a).nsfw_detection_pb.ImageDetectionResponseb\x06proto3'
)

_CLASSIFICATIONS = _descriptor.EnumDescriptor(
  name='Classifications',
  full_name='nsfw_detection_pb.Classifications',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Safe', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ProbablySafe', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ProbablyUnsafe', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Unsafe', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=470,
  serialized_end=547,
)
_sym_db.RegisterEnumDescriptor(_CLASSIFICATIONS)

Classifications = enum_type_wrapper.EnumTypeWrapper(_CLASSIFICATIONS)
Safe = 0
ProbablySafe = 1
ProbablyUnsafe = 2
Unsafe = 3



_UNSAFEFRAME = _descriptor.Descriptor(
  name='UnsafeFrame',
  full_name='nsfw_detection_pb.UnsafeFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='second', full_name='nsfw_detection_pb.UnsafeFrame.second', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nsfw_probability', full_name='nsfw_detection_pb.UnsafeFrame.nsfw_probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=88,
)


_DETECTFROMVIDEOREQUEST = _descriptor.Descriptor(
  name='DetectFromVideoRequest',
  full_name='nsfw_detection_pb.DetectFromVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='video', full_name='nsfw_detection_pb.DetectFromVideoRequest.video', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_format', full_name='nsfw_detection_pb.DetectFromVideoRequest.video_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=151,
)


_DETECTFROMIMAGEREQUEST = _descriptor.Descriptor(
  name='DetectFromImageRequest',
  full_name='nsfw_detection_pb.DetectFromImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='nsfw_detection_pb.DetectFromImageRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_format', full_name='nsfw_detection_pb.DetectFromImageRequest.image_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=214,
)


_VIDEODETECTIONRESPONSE = _descriptor.Descriptor(
  name='VideoDetectionResponse',
  full_name='nsfw_detection_pb.VideoDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='classification', full_name='nsfw_detection_pb.VideoDetectionResponse.classification', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsafe_frames', full_name='nsfw_detection_pb.VideoDetectionResponse.unsafe_frames', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=356,
)


_IMAGEDETECTIONRESPONSE = _descriptor.Descriptor(
  name='ImageDetectionResponse',
  full_name='nsfw_detection_pb.ImageDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='classification', full_name='nsfw_detection_pb.ImageDetectionResponse.classification', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nsfw_probability', full_name='nsfw_detection_pb.ImageDetectionResponse.nsfw_probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=468,
)

_VIDEODETECTIONRESPONSE.fields_by_name['classification'].enum_type = _CLASSIFICATIONS
_VIDEODETECTIONRESPONSE.fields_by_name['unsafe_frames'].message_type = _UNSAFEFRAME
_IMAGEDETECTIONRESPONSE.fields_by_name['classification'].enum_type = _CLASSIFICATIONS
DESCRIPTOR.message_types_by_name['UnsafeFrame'] = _UNSAFEFRAME
DESCRIPTOR.message_types_by_name['DetectFromVideoRequest'] = _DETECTFROMVIDEOREQUEST
DESCRIPTOR.message_types_by_name['DetectFromImageRequest'] = _DETECTFROMIMAGEREQUEST
DESCRIPTOR.message_types_by_name['VideoDetectionResponse'] = _VIDEODETECTIONRESPONSE
DESCRIPTOR.message_types_by_name['ImageDetectionResponse'] = _IMAGEDETECTIONRESPONSE
DESCRIPTOR.enum_types_by_name['Classifications'] = _CLASSIFICATIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnsafeFrame = _reflection.GeneratedProtocolMessageType('UnsafeFrame', (_message.Message,), {
  'DESCRIPTOR' : _UNSAFEFRAME,
  '__module__' : 'nsfw_pb2'
  # @@protoc_insertion_point(class_scope:nsfw_detection_pb.UnsafeFrame)
  })
_sym_db.RegisterMessage(UnsafeFrame)

DetectFromVideoRequest = _reflection.GeneratedProtocolMessageType('DetectFromVideoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTFROMVIDEOREQUEST,
  '__module__' : 'nsfw_pb2'
  # @@protoc_insertion_point(class_scope:nsfw_detection_pb.DetectFromVideoRequest)
  })
_sym_db.RegisterMessage(DetectFromVideoRequest)

DetectFromImageRequest = _reflection.GeneratedProtocolMessageType('DetectFromImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTFROMIMAGEREQUEST,
  '__module__' : 'nsfw_pb2'
  # @@protoc_insertion_point(class_scope:nsfw_detection_pb.DetectFromImageRequest)
  })
_sym_db.RegisterMessage(DetectFromImageRequest)

VideoDetectionResponse = _reflection.GeneratedProtocolMessageType('VideoDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VIDEODETECTIONRESPONSE,
  '__module__' : 'nsfw_pb2'
  # @@protoc_insertion_point(class_scope:nsfw_detection_pb.VideoDetectionResponse)
  })
_sym_db.RegisterMessage(VideoDetectionResponse)

ImageDetectionResponse = _reflection.GeneratedProtocolMessageType('ImageDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETECTIONRESPONSE,
  '__module__' : 'nsfw_pb2'
  # @@protoc_insertion_point(class_scope:nsfw_detection_pb.ImageDetectionResponse)
  })
_sym_db.RegisterMessage(ImageDetectionResponse)



_NSFWDETECTIONPROTOSERVICE = _descriptor.ServiceDescriptor(
  name='NsfwDetectionProtoService',
  full_name='nsfw_detection_pb.NsfwDetectionProtoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=550,
  serialized_end=787,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectFromVideo',
    full_name='nsfw_detection_pb.NsfwDetectionProtoService.DetectFromVideo',
    index=0,
    containing_service=None,
    input_type=_DETECTFROMVIDEOREQUEST,
    output_type=_VIDEODETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetectFromImage',
    full_name='nsfw_detection_pb.NsfwDetectionProtoService.DetectFromImage',
    index=1,
    containing_service=None,
    input_type=_DETECTFROMIMAGEREQUEST,
    output_type=_IMAGEDETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NSFWDETECTIONPROTOSERVICE)

DESCRIPTOR.services_by_name['NsfwDetectionProtoService'] = _NSFWDETECTIONPROTOSERVICE

# @@protoc_insertion_point(module_scope)
